plugins {
	id 'java'
  id 'org.springframework.boot' version '3.5.7'
  id 'io.spring.dependency-management' version '1.1.7'
  id 'com.diffplug.spotless' version '7.0.4'
}

group = 'com.flowbi'
version = '0.0.1-SNAPSHOT'

ext['testcontainers.version'] = '1.21.4'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-data-redis'
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.session:spring-session-data-redis'
	implementation 'org.flywaydb:flyway-core'
	implementation 'org.springframework.security:spring-security-crypto'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
  	implementation 'org.springframework.boot:spring-boot-starter-web'
  	//swagger
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.17'
  	compileOnly 'org.projectlombok:lombok'
	//runtimeOnly 'com.mysql:mysql-connector-j'
	runtimeOnly 'com.h2database:h2'
	runtimeOnly 'org.flywaydb:flyway-database-postgresql'
	runtimeOnly 'org.postgresql:postgresql'
	annotationProcessor 'org.projectlombok:lombok'
	annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
	// testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa-test'
	// testImplementation 'org.springframework.boot:spring-boot-starter-data-redis-test'
	testImplementation 'org.springframework.security:spring-security-test'
	// testImplementation 'org.springframework.boot:spring-boot-starter-validation-test'
  	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.testcontainers:junit-jupiter'
	testImplementation 'org.testcontainers:postgresql'
  	testCompileOnly 'org.projectlombok:lombok'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	testAnnotationProcessor 'org.projectlombok:lombok'
}

tasks.named('test') {
	useJUnitPlatform()
}

springBoot {
	buildInfo()
}

//코드 포맷팅 코드
spotless {
  java {
    eclipse().configFile('config/eclipse-formatter.xml')
    removeUnusedImports()
    trimTrailingWhitespace()
    endWithNewline()
  }
}
