/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/auth/refresh': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** 토큰 재발급 */
    post: operations['refresh']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** 로그아웃 */
    post: operations['logout']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** 로그인 */
    post: operations['login']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    RefreshTokenRequest: {
      /** @description 리프레시 토큰 */
      refresh_token: string
    }
    ApiResponseAuthTokenResponse: {
      success?: boolean
      data?: components['schemas']['AuthTokenResponse']
      message?: string
    }
    AuthTokenResponse: {
      /** @description 액세스 토큰 */
      access_token?: string
      /** @description 리프레시 토큰 */
      refresh_token?: string
      /**
       * @description 토큰 타입
       * @example Bearer
       */
      token_type?: string
      /**
       * Format: int64
       * @description 액세스 토큰 만료까지 남은 초
       * @example 1800
       */
      expires_in?: number
      /** @description 로그인 사용자 */
      user?: components['schemas']['AuthUserResponse']
    }
    AuthUserResponse: {
      /**
       * Format: int64
       * @description 사용자 ID
       * @example 1
       */
      user_id?: number
      /**
       * @description 사번
       * @example EMP001
       */
      employee_number?: string
      /**
       * @description 이름
       * @example 홍길동
       */
      name?: string
    }
    LogoutRequest: {
      /** @description 폐기할 현재 기기의 리프레시 토큰 */
      refresh_token: string
    }
    ApiResponseLogoutResponse: {
      success?: boolean
      data?: components['schemas']['LogoutResponse']
      message?: string
    }
    LogoutResponse: {
      /**
       * @description 폐기 완료 여부
       * @example true
       */
      revoked?: boolean
    }
    LoginRequest: {
      /**
       * @description 사번
       * @example EMP001
       */
      employee_number: string
      /**
       * @description 비밀번호
       * @example password123
       */
      password: string
      /**
       * @description 접속 기기 정보
       * @example Chrome on macOS
       */
      device_info?: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  refresh: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RefreshTokenRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseAuthTokenResponse']
        }
      }
    }
  }
  logout: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LogoutRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseLogoutResponse']
        }
      }
    }
  }
  login: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseAuthTokenResponse']
        }
      }
    }
  }
}
