/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/rooms/{roomId}/reservations': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 회의실 예약 현황 조회 */
    get: operations['findReservations']
    put?: never
    /** 회의실 예약 생성 */
    post: operations['createReservation']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/rooms': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 회의실 목록 조회 */
    get: operations['findRooms']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/schedules': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 캘린더 일정 조회 */
    get: operations['findCalendar']
    put?: never
    /** 일정 생성 */
    post: operations['create']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/refresh': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** 토큰 재발급 */
    post: operations['refresh']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** 로그아웃 */
    post: operations['logout']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** 로그인 */
    post: operations['login']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/schedules/{scheduleId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 일정 상세 조회 */
    get: operations['findById']
    put?: never
    post?: never
    /** 일정 삭제 */
    delete: operations['delete']
    options?: never
    head?: never
    /** 일정 수정 */
    patch: operations['update']
    trace?: never
  }
  '/api/v1/rooms/reservations/{reservationId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** 회의실 예약 취소 */
    delete: operations['cancelReservation']
    options?: never
    head?: never
    /** 회의실 예약 수정 */
    patch: operations['updateReservation']
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    ReservationRequest: {
      /**
       * Format: int64
       * @description 변경할 회의실 ID
       * @example 2
       */
      room_id?: number
      /**
       * @description 예약 제목
       * @example 기획 회의
       */
      title: string
      /**
       * Format: date-time
       * @description 예약 시작 일시
       * @example 2026-07-05T09:00:00
       */
      start_at: string
      /**
       * Format: date-time
       * @description 예약 종료 일시
       * @example 2026-07-05T10:00:00
       */
      end_at: string
      /**
       * Format: int32
       * @description 이용 예상 인원
       * @example 5
       */
      count?: number
      /** @description 회의 상세 설명 */
      field?: string
      /**
       * @description 일정 유형
       * @example PERSONAL
       * @enum {string}
       */
      schedule_type?: 'PERSONAL' | 'TEAM' | 'PROJECT'
      /**
       * @description 열람 가능 범위
       * @example PRIVATE
       * @enum {string}
       */
      visibility?: 'PUBLIC' | 'PRIVATE' | 'TEAM_ONLY'
      /**
       * @description 일정 색상 라벨
       * @example 파랑
       */
      color_label?: string
      /** @description 일정 공유 대상 목록 */
      targets?: components['schemas']['ScheduleTargetRequest'][]
    }
    ApiResponseReservationResponse: {
      success?: boolean
      data?: components['schemas']['ReservationResponse']
      message?: string
    }
    ReservationResponse: {
      /**
       * Format: int64
       * @description 예약 ID
       */
      reservation_id?: number
      /**
       * Format: int64
       * @description 회의실 ID
       */
      room_id?: number
      /**
       * Format: int64
       * @description 연동 일정 ID
       */
      schedule_id?: number
      /** @description 예약 제목 */
      title?: string
      /**
       * Format: date-time
       * @description 예약 시작 일시
       */
      start_at?: string
      /**
       * Format: date-time
       * @description 예약 종료 일시
       */
      end_at?: string
      /**
       * @description 예약 상태
       * @enum {string}
       */
      status?: 'PENDING' | 'RESERVED' | 'CANCELLED'
      /**
       * Format: date-time
       * @description 취소 일시
       */
      cancelled_at?: string
      /**
       * Format: int32
       * @description 이용 예상 인원
       */
      count?: number
      /** @description 회의 상세 설명 */
      field?: string
      /**
       * Format: int64
       * @description 예약자 ID
       */
      creator_id?: number
      /** @description 예약자 이름 */
      creator_name?: string
      /** @description 예약 팀명 */
      team_name?: string
    }
    ApiResponseListRoomResponse: {
      success?: boolean
      data?: components['schemas']['RoomResponse'][]
      message?: string
    }
    RoomResponse: {
      /**
       * Format: int64
       * @description 회의실 ID
       */
      room_id?: number
      /** @description 회의실 이름 */
      room_name?: string
      /**
       * Format: int64
       * @description 수용 인원
       */
      capacity?: number
      /** @description 위치 */
      location?: string
      /** @description 장비/비고 */
      field?: string
      /** @description 조회 날짜의 예약 목록 */
      reservations?: components['schemas']['ReservationResponse'][]
    }
    ApiResponseListReservationResponse: {
      success?: boolean
      data?: components['schemas']['ReservationResponse'][]
      message?: string
    }
    ScheduleRequest: {
      /**
       * @description 일정 제목
       * @example 주간 회의
       */
      title: string
      /**
       * @description 일정 유형
       * @example TEAM
       * @enum {string}
       */
      schedule_type: 'PERSONAL' | 'TEAM' | 'PROJECT'
      /**
       * @description 열람 가능 범위
       * @example PRIVATE
       * @enum {string}
       */
      visibility: 'PUBLIC' | 'PRIVATE' | 'TEAM_ONLY'
      /**
       * Format: date-time
       * @description 시작 일시
       * @example 2026-07-05T09:00:00
       */
      start_at: string
      /**
       * Format: date-time
       * @description 종료 일시
       * @example 2026-07-05T10:00:00
       */
      end_at: string
      /**
       * @description 색상 라벨
       * @example 파랑
       */
      color_label?: string
      /**
       * @description 장소
       * @example 본관 3층
       */
      location?: string
      /** @description 일정 상세 설명 */
      content?: string
      /** @description 공유 대상 목록 */
      targets?: components['schemas']['ScheduleTargetRequest'][]
    }
    ScheduleTargetRequest: {
      /**
       * @description 공유 대상 유형
       * @example USER
       * @enum {string}
       */
      target_type: 'USER' | 'PROJECT' | 'TEAM'
      /**
       * Format: int64
       * @description 사용자 ID
       */
      user_id?: number
      /**
       * Format: int64
       * @description 프로젝트 ID
       */
      project_id?: number
      /**
       * Format: int64
       * @description 공유 기준 상위 팀 ID
       */
      ancestor_team_id?: number
      /**
       * Format: int64
       * @description 팀 ID
       */
      team_id?: number
    }
    ApiResponseScheduleResponse: {
      success?: boolean
      data?: components['schemas']['ScheduleResponse']
      message?: string
    }
    ScheduleResponse: {
      /**
       * Format: int64
       * @description 일정 ID
       */
      schedule_id?: number
      /** @description 일정 제목 */
      title?: string
      /**
       * @description 일정 유형
       * @enum {string}
       */
      schedule_type?: 'PERSONAL' | 'TEAM' | 'PROJECT'
      /**
       * @description 열람 가능 범위
       * @enum {string}
       */
      visibility?: 'PUBLIC' | 'PRIVATE' | 'TEAM_ONLY'
      /**
       * Format: date-time
       * @description 시작 일시
       */
      start_at?: string
      /**
       * Format: date-time
       * @description 종료 일시
       */
      end_at?: string
      /**
       * Format: int64
       * @description 등록자 ID
       */
      creator_id?: number
      /** @description 색상 라벨 */
      color_label?: string
      /** @description 장소 */
      location?: string
      /** @description 일정 상세 설명 */
      content?: string
      /** @description 공유 대상 목록 */
      targets?: components['schemas']['ScheduleTargetResponse'][]
    }
    ScheduleTargetResponse: {
      /**
       * @description 공유 대상 유형
       * @enum {string}
       */
      target_type?: 'USER' | 'PROJECT' | 'TEAM'
      /**
       * Format: int64
       * @description 사용자 ID
       */
      user_id?: number
      /**
       * Format: int64
       * @description 프로젝트 ID
       */
      project_id?: number
      /**
       * Format: int64
       * @description 공유 기준 상위 팀 ID
       */
      ancestor_team_id?: number
      /**
       * Format: int64
       * @description 팀 ID
       */
      team_id?: number
    }
    RefreshTokenRequest: {
      /** @description 리프레시 토큰 */
      refresh_token: string
    }
    ApiResponseAuthTokenResponse: {
      success?: boolean
      data?: components['schemas']['AuthTokenResponse']
      message?: string
    }
    AuthTokenResponse: {
      /** @description 액세스 토큰 */
      access_token?: string
      /** @description 리프레시 토큰 */
      refresh_token?: string
      /**
       * @description 토큰 타입
       * @example Bearer
       */
      token_type?: string
      /**
       * Format: int64
       * @description 액세스 토큰 만료까지 남은 초
       * @example 1800
       */
      expires_in?: number
      /** @description 로그인 사용자 */
      user?: components['schemas']['AuthUserResponse']
    }
    AuthUserResponse: {
      /**
       * Format: int64
       * @description 사용자 ID
       * @example 1
       */
      user_id?: number
      /**
       * @description 사번
       * @example EMP001
       */
      employee_number?: string
      /**
       * @description 이름
       * @example 홍길동
       */
      name?: string
    }
    LogoutRequest: {
      /** @description 폐기할 현재 기기의 리프레시 토큰 */
      refresh_token: string
    }
    ApiResponseLogoutResponse: {
      success?: boolean
      data?: components['schemas']['LogoutResponse']
      message?: string
    }
    LogoutResponse: {
      /**
       * @description 폐기 완료 여부
       * @example true
       */
      revoked?: boolean
    }
    LoginRequest: {
      /**
       * @description 사번
       * @example EMP001
       */
      employee_number: string
      /**
       * @description 비밀번호
       * @example password123
       */
      password: string
      /**
       * @description 접속 기기 정보
       * @example Chrome on macOS
       */
      device_info?: string
    }
    ApiResponseListScheduleResponse: {
      success?: boolean
      data?: components['schemas']['ScheduleResponse'][]
      message?: string
    }
    ApiResponseVoid: {
      success?: boolean
      data?: Record<string, never>
      message?: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  findReservations: {
    parameters: {
      query: {
        date: string
      }
      header?: never
      path: {
        roomId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseListReservationResponse']
        }
      }
    }
  }
  createReservation: {
    parameters: {
      query?: never
      header?: never
      path: {
        roomId: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ReservationRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseReservationResponse']
        }
      }
    }
  }
  findRooms: {
    parameters: {
      query?: {
        capacity?: number
        date?: string
        timeRange?: string
        status?: 'PENDING' | 'RESERVED' | 'CANCELLED'
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseListRoomResponse']
        }
      }
    }
  }
  findCalendar: {
    parameters: {
      query?: {
        view?: string
        date?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseListScheduleResponse']
        }
      }
    }
  }
  create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ScheduleRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseScheduleResponse']
        }
      }
    }
  }
  refresh: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RefreshTokenRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseAuthTokenResponse']
        }
      }
    }
  }
  logout: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LogoutRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseLogoutResponse']
        }
      }
    }
  }
  login: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseAuthTokenResponse']
        }
      }
    }
  }
  findById: {
    parameters: {
      query?: never
      header?: never
      path: {
        scheduleId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseScheduleResponse']
        }
      }
    }
  }
  delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        scheduleId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
    }
  }
  update: {
    parameters: {
      query?: never
      header?: never
      path: {
        scheduleId: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ScheduleRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseScheduleResponse']
        }
      }
    }
  }
  cancelReservation: {
    parameters: {
      query?: never
      header?: never
      path: {
        reservationId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
    }
  }
  updateReservation: {
    parameters: {
      query?: never
      header?: never
      path: {
        reservationId: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ReservationRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseReservationResponse']
        }
      }
    }
  }
}
