-- Initial Calendar baseline. User, team and project ownership remains with their respective domains;
-- this migration only establishes the foreign-key targets required by Calendar.
CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS teams (
    team_id BIGINT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS projects (
    project_id BIGINT PRIMARY KEY
);

CREATE TABLE schedules (
    schedule_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    schedule_type VARCHAR(30) NULL,
    visibility VARCHAR(30) NULL,
    start_at TIMESTAMP WITH TIME ZONE NOT NULL,
    end_at TIMESTAMP WITH TIME ZONE NOT NULL,
    creator_id BIGINT NOT NULL,
    CONSTRAINT fk_schedules_creator FOREIGN KEY (creator_id) REFERENCES users (user_id)
);

CREATE TABLE schedules_details (
    schedule_details_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_id BIGINT NOT NULL,
    content VARCHAR(200) NULL,
    location VARCHAR(30) NULL,
    CONSTRAINT fk_schedule_details_schedule FOREIGN KEY (schedule_id) REFERENCES schedules (schedule_id)
);

CREATE TABLE schedule_targets (
    schedule_target_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_id BIGINT NOT NULL,
    user_id BIGINT NULL,
    team_id BIGINT NULL,
    project_id BIGINT NULL,
    target_type VARCHAR(30) NOT NULL,
    CONSTRAINT fk_schedule_targets_schedule FOREIGN KEY (schedule_id) REFERENCES schedules (schedule_id),
    CONSTRAINT fk_schedule_targets_user FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT fk_schedule_targets_team FOREIGN KEY (team_id) REFERENCES teams (team_id),
    CONSTRAINT fk_schedule_targets_project FOREIGN KEY (project_id) REFERENCES projects (project_id)
);
