ALTER TABLE schedules ADD COLUMN status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE schedules ADD COLUMN cancelled_at TIMESTAMP WITH TIME ZONE NULL;
ALTER TABLE schedules ADD COLUMN cancelled_by BIGINT NULL;
ALTER TABLE schedules ADD COLUMN is_all_day BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE schedules ADD COLUMN color_label VARCHAR(30) NOT NULL DEFAULT 'BLUE';
ALTER TABLE schedules ADD COLUMN creator_attends BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE schedules ADD CONSTRAINT fk_schedules_cancelled_by
    FOREIGN KEY (cancelled_by) REFERENCES users (user_id);
ALTER TABLE schedules ADD CONSTRAINT ck_schedules_type
    CHECK (schedule_type IN ('PERSONAL', 'TEAM', 'PROJECT'));
ALTER TABLE schedules ADD CONSTRAINT ck_schedules_visibility
    CHECK (visibility IN ('PRIVATE', 'TEAM', 'PROJECT'));
ALTER TABLE schedules ADD CONSTRAINT ck_schedules_type_visibility CHECK (
    (schedule_type = 'PERSONAL' AND visibility = 'PRIVATE') OR
    (schedule_type = 'TEAM' AND visibility = 'TEAM') OR
    (schedule_type = 'PROJECT' AND visibility = 'PROJECT')
);
ALTER TABLE schedules ADD CONSTRAINT ck_schedules_time CHECK (end_at > start_at);
ALTER TABLE schedules ADD CONSTRAINT ck_schedules_status CHECK (status IN ('ACTIVE', 'CANCELED'));
ALTER TABLE schedules ADD CONSTRAINT ck_schedules_cancellation CHECK (
    (status = 'ACTIVE' AND cancelled_at IS NULL AND cancelled_by IS NULL) OR
    (status = 'CANCELED' AND cancelled_at IS NOT NULL AND cancelled_by IS NOT NULL)
);
ALTER TABLE schedules ADD CONSTRAINT ck_schedules_color
    CHECK (color_label IN ('RED', 'ORANGE', 'YELLOW', 'GREEN', 'BLUE', 'PURPLE'));

ALTER TABLE schedules_details ADD CONSTRAINT uq_schedule_details_schedule UNIQUE (schedule_id);
ALTER TABLE schedule_targets ADD CONSTRAINT ck_schedule_targets_shape CHECK (
    (target_type = 'USER' AND user_id IS NOT NULL AND team_id IS NULL AND project_id IS NULL) OR
    (target_type = 'TEAM' AND user_id IS NULL AND team_id IS NOT NULL AND project_id IS NULL) OR
    (target_type = 'PROJECT' AND user_id IS NULL AND team_id IS NULL AND project_id IS NOT NULL)
);

CREATE TABLE schedule_participants (
    schedule_participant_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_schedule_participants_schedule FOREIGN KEY (schedule_id) REFERENCES schedules (schedule_id),
    CONSTRAINT fk_schedule_participants_user FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT uq_schedule_participants_schedule_user UNIQUE (schedule_id, user_id)
);

CREATE INDEX idx_schedules_active_period ON schedules (status, start_at, end_at);
CREATE INDEX idx_schedules_creator ON schedules (creator_id);
CREATE INDEX idx_schedule_participants_user ON schedule_participants (user_id, schedule_id);
CREATE INDEX idx_schedule_targets_user ON schedule_targets (user_id, schedule_id);
CREATE INDEX idx_schedule_targets_team ON schedule_targets (team_id, schedule_id);
CREATE INDEX idx_schedule_targets_project ON schedule_targets (project_id, schedule_id);
