ALTER TABLE projects ADD COLUMN project_name VARCHAR(50) NOT NULL DEFAULT 'Unassigned project';
ALTER TABLE projects ADD COLUMN status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE';

CREATE TABLE projects_members (
    project_member_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    joined_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_projects_members_project FOREIGN KEY (project_id) REFERENCES projects (project_id),
    CONSTRAINT fk_projects_members_user FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT uq_projects_members_project_user UNIQUE (project_id, user_id)
);

CREATE INDEX idx_projects_members_user ON projects_members (user_id, project_id);
