CREATE TABLE rooms (
    room_id BIGINT PRIMARY KEY,
    room_name VARCHAR(100) NOT NULL,
    capacity BIGINT NULL,
    location VARCHAR(255) NULL
);

CREATE TABLE rooms_reservations (
    reservation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id BIGINT NOT NULL,
    schedule_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    start_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    status VARCHAR(30) NOT NULL,
    CONSTRAINT fk_room_reservations_room FOREIGN KEY (room_id) REFERENCES rooms (room_id),
    CONSTRAINT fk_room_reservations_schedule FOREIGN KEY (schedule_id)
        REFERENCES schedules (schedule_id),
    CONSTRAINT ck_room_reservations_time CHECK (end_at > start_at),
    CONSTRAINT ck_room_reservations_status CHECK (status IN ('RESERVED', 'CANCELED'))
);

CREATE INDEX idx_room_reservations_active_period
    ON rooms_reservations (room_id, status, start_at, end_at);
CREATE INDEX idx_room_reservations_schedule ON rooms_reservations (schedule_id);
