CREATE TABLE IF NOT EXISTS schedules (
    schedule_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    schedule_type VARCHAR(30),
    visibility VARCHAR(30),
    start_at TIMESTAMP NOT NULL,
    end_at TIMESTAMP NOT NULL,
    creator_id BIGINT NOT NULL,
    color_label VARCHAR(20),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_schedules_creator_id FOREIGN KEY (creator_id) REFERENCES users(user_id)
);

CREATE TABLE IF NOT EXISTS schedules_details (
    schedule_details_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_id BIGINT NOT NULL,
    content VARCHAR(200),
    location VARCHAR(30),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_schedules_details_schedule_id FOREIGN KEY (schedule_id) REFERENCES schedules(schedule_id)
);

CREATE TABLE IF NOT EXISTS projects (
    project_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_name VARCHAR(50) NOT NULL,
    description TEXT,
    status VARCHAR(30),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS projects_members (
    project_member_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_projects_members_project_id FOREIGN KEY (project_id) REFERENCES projects(project_id),
    CONSTRAINT fk_projects_members_user_id FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE TABLE IF NOT EXISTS schedule_targets (
    schedule_target_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_id BIGINT NOT NULL,
    user_id BIGINT,
    project_id BIGINT,
    ancestor_team_id BIGINT,
    team_id BIGINT,
    target_type VARCHAR(30) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_schedule_targets_schedule_id FOREIGN KEY (schedule_id) REFERENCES schedules(schedule_id),
    CONSTRAINT fk_schedule_targets_user_id FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT fk_schedule_targets_project_id FOREIGN KEY (project_id) REFERENCES projects(project_id)
);

CREATE INDEX IF NOT EXISTS idx_schedules_creator_range ON schedules (creator_id, start_at, end_at);
CREATE INDEX IF NOT EXISTS idx_schedules_range ON schedules (start_at, end_at);
CREATE INDEX IF NOT EXISTS idx_schedule_targets_user ON schedule_targets (target_type, user_id, schedule_id);
CREATE INDEX IF NOT EXISTS idx_schedule_targets_team ON schedule_targets (target_type, ancestor_team_id, team_id, schedule_id);
CREATE INDEX IF NOT EXISTS idx_schedule_targets_project ON schedule_targets (target_type, project_id, schedule_id);
CREATE INDEX IF NOT EXISTS idx_projects_members_user_project ON projects_members (user_id, project_id);
CREATE INDEX IF NOT EXISTS idx_projects_members_project_user ON projects_members (project_id, user_id);
