CREATE TABLE IF NOT EXISTS rooms (
    room_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_name VARCHAR(100) NOT NULL,
    capacity BIGINT,
    location VARCHAR(255),
    field VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS rooms_reservations (
    reservation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id BIGINT NOT NULL,
    schedule_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    start_at TIMESTAMP NOT NULL,
    end_at TIMESTAMP NOT NULL,
    status VARCHAR(30),
    cancelled_at TIMESTAMP,
    count INT,
    field VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_rooms_reservations_room_id FOREIGN KEY (room_id) REFERENCES rooms(room_id),
    CONSTRAINT fk_rooms_reservations_schedule_id FOREIGN KEY (schedule_id) REFERENCES schedules(schedule_id)
);

CREATE INDEX IF NOT EXISTS idx_rooms_capacity ON rooms (capacity);
CREATE INDEX IF NOT EXISTS idx_room_reservations_room_range_status
    ON rooms_reservations (room_id, start_at, end_at, status);
CREATE INDEX IF NOT EXISTS idx_room_reservations_schedule_id
    ON rooms_reservations (schedule_id);

INSERT INTO rooms (room_name, capacity, location, field)
SELECT '1회의실', 6, '본관 3층 301호', '화이트보드, 모니터'
WHERE NOT EXISTS (SELECT 1 FROM rooms WHERE room_name = '1회의실');

INSERT INTO rooms (room_name, capacity, location, field)
SELECT '대회의실', 20, '본관 5층 501호', '빔프로젝터, 화상회의'
WHERE NOT EXISTS (SELECT 1 FROM rooms WHERE room_name = '대회의실');

INSERT INTO rooms (room_name, capacity, location, field)
SELECT '집중회의실', 4, '별관 2층 204호', '모니터'
WHERE NOT EXISTS (SELECT 1 FROM rooms WHERE room_name = '집중회의실');
